version: 0.2

phases:
  pre_build:
     commands:
      - pip3 install awscli --upgrade --user
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain gamedoora --domain-owner 727903310356  --query authorizationToken --output text`
     
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean install --settings settings.xml
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
